### ISSUE TITLE
Unwanted row highlights

### ISSUE THREAD

**Issue by maria-le** [pdelanauze/sweet-material-table#1]
When you select rows with the check box in the left column, unrelated rows are highlighted at the top of the table.

The number of unwanted highlighted rows equals the number of rows that are selected.

**Comment by pdelanauze** [comment]
will take a look tomorrow , you have a screenshot by any chance?

**Comment by pdelanauze** [comment]
ah , nevermind for the screenshot part, easy to reproduce .. will get that fixed tomorrow. thanks for mentioning. keep em coming
